# Generated by Django 3.2.5 on 2021-07-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coating',
        ),
        migrations.DeleteModel(
            name='Composites',
        ),
        migrations.DeleteModel(
            name='Door',
        ),
        migrations.DeleteModel(
            name='Flooring_tiles',
        ),
        migrations.DeleteModel(
            name='gypsum_board',
        ),
        migrations.DeleteModel(
            name='Lift',
        ),
        migrations.DeleteModel(
            name='Plugs_sockets',
        ),
        migrations.DeleteModel(
            name='Steel_framing',
        ),
        migrations.DeleteModel(
            name='Switches',
        ),
        migrations.DeleteModel(
            name='Wall_covering',
        ),
    ]
