# Generated by Django 3.2.5 on 2021-07-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20210714_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Floors',
            new_name='Floor',
        ),
    ]
