# Generated by Django 3.2.5 on 2021-07-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_rename_floors_floor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plastics',
            new_name='Plastic',
        ),
    ]
